version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: billing-system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/resources/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./src/main/resources/keycloak_backup20231015232328.sql:/docker-entrypoint-initdb.d/keycloak_backup20231015232328.sql
