spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billing_system
    username: root
    password: FinanceW!se@June21
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
logging:
  level:
    root: INFO
  file:
    name: myapp.log