name: Build Java Application

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use the desired Java version
          distribution: 'zulu'

      - name: Build the application
        run: ./gradlew clean build # Use the Gradle wrapper script with your desired tasks
